version: '3.7'
services:
    listed:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        expose: 
            - 80
        volumes:
            - app:/app
            - /node_modules
        environment: 
            VIRTUAL_HOST: listed.mdomzalski.pl,www.listed.mdomzalski.pl
        container_name: listed
volumes:
    app:
networks:
    default:
        external:
            name: nginx-proxy
