version: '3'
services:
  listed:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    expose:
      - 80
    container_name: listed.mdomzalski.pl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.listed.rule=Host(`listed.mdomzalski.pl`,`www.listed.mdomzalski.pl`)"
      - "traefik.http.routers.listed.entrypoints=websecure"
      - "traefik.http.routers.listed.tls.certresolver=production"
      - "traefik.http.routers.listed-https.tls=true"
      - "traefik.http.routers.listed-https.rule=Host(`listed.mdomzalski.pl`,`www.listed.mdomzalski.pl`)"
      - "traefik.http.routers.listed-https.entrypoints=websecure"
      - "traefik.http.routers.listed-https.service=listed"
      - "traefik.http.services.listed.loadbalancer.server.port=80"
networks:
  default:
    name: traefik
    external: true
