version: '3.7'
services:
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        ports:
            - 3000:3000
        volumes:
            - ./:/app
        depends_on: 
            - backend
        networks:
            - listed