version: '3.7'
services:
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        ports:
            - 3000:3000
        volumes:
            - ./:/app
            - /node_modules
        environment: 
            VIRTUAL_HOST: listed.mdomzalski.pl,www.listed.mdomzalski.pl
networks:
    default:
        external:
            name: nginx-proxy
