version: '3.7'
services:
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        expose: 
            - 80
        volumes:
            - app:/app/build
            - /node_modules
        environment: 
            VIRTUAL_HOST: listed.mdomzalski.pl,www.listed.mdomzalski.pl
volumes:
    app:
networks:
    default:
        external:
            name: nginx-proxy
